# Generated by Django 4.0.4 on 2022-04-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supertypes',
            old_name='type',
            new_name='super_type',
        ),
    ]
