# Generated by Django 4.0.4 on 2022-05-01 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0002_rename_type_supertypes_super_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supertypes',
            old_name='super_type',
            new_name='type',
        ),
    ]
