# Generated by Django 4.0.4 on 2022-04-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supers',
            name='super_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_types.supertypes'),
        ),
    ]
