# Generated by Django 4.0.4 on 2022-05-01 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_rename_super_type_supers_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='type',
            new_name='super_type',
        ),
    ]
