# Generated by Django 4.0.4 on 2022-05-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0003_rename_super_type_supertypes_type'),
        ('supers', '0005_alter_supers_super_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supers',
            name='super_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_types.supertypes'),
        ),
    ]
